CREATE DATABASE MANAGE_TEST_SCORES;
USE MANAGE_TEST_SCORES;
CREATE TABLE STUDENT (
ID INT auto_increment primary KEY,
NAME VARCHAR(50) NOT NULL,
BIRTHDAY DATE NOT NULL,
CLASS VARCHAR(10) NOT NULL,
INTRODUCE VARCHAR(250) NOT NULL
);
CREATE TABLE SUBJECT (
ID INT auto_increment primary KEY,
NAME VARCHAR(50) NOT NULL,
TEACHER_ID INT NOT NULL
);
CREATE TABLE TRANSCRIPT (
ID INT auto_increment primary KEY,
STUDENT_ID INT NOT NULL,
SUBJECT_ID INT NOT NULL,
SCORE double NOT NULL,
TEST_DAY DATE NOT NULL
);
CREATE TABLE TEACHER (
ID INT auto_increment primary KEY,
NAME varchar(50) NOT NULL,
PHONE varchar(10) NOT NULL
);
ALTER TABLE TRANSCRIPT ADD constraint foreign key (STUDENT_ID) references STUDENT(ID);
ALTER TABLE TRANSCRIPT ADD constraint foreign key (SUBJECT_ID) references SUBJECT(ID);
ALTER TABLE SUBJECT ADD constraint foreign key (TEACHER_ID) references TEACHER(ID);
