CREATE DATABASE SHOPEE;
USE SHOPEE;
CREATE TABLE USER (
ID INT auto_increment primary KEY,
NAME varchar(50) NOT NULL,
PHONE varchar(10) NOT NULL unique,
EMAIL varchar(50) NOT NULL unique,
PASSWORD VARCHAR(50) NOT NULL
);
CREATE TABLE CART (
ID INT auto_increment PRIMARY KEY,
USER_ID INT NOT NULL unique,
CARTLINE_ID INT NOT NULL,
TOTAL BIGINT NOT NULL
);
CREATE TABLE CART_LINE (
ID INT auto_increment primary KEY,
PRODUCT_ID INT NOT NULL,
CART_ID INT NOT NULL,
VARIANT_ID INT NOT NULL,
SUBTOTAL BIGINT NOT NULL
);
CREATE TABLE CATEGORY (
ID INT auto_increment primary KEY,
NAME varchar(50) NOT NULL
);
CREATE TABLE PRODUCT (
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
PRICE BIGINT NOT NULL,
CATEGORY_ID INT NOT NULL
);
CREATE TABLE VARIANT (
ID INT auto_increment primary KEY,
SIZE INT NOT NULL,
COLOR VARCHAR(10),
PRODUCT_ID INT NOT NULL
);
CREATE TABLE ORDERS (
ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT NOT NULL,
ORDER_LINE_ID INT NOT NULL,
TOTAL BIGINT NOT NULL
);
CREATE TABLE ORDER_LINE (
ID INT auto_increment primary KEY,
CART_LINE_ID INT NOT NULL,
SUBTOTAL BIGINT NOT NULL
);
ALTER TABLE CART ADD constraint foreign key (USER_ID) references USER(ID);
ALTER TABLE CART rename column CARTLINE_ID TO CART_LINE_ID;
ALTER TABLE CART ADD constraint foreign key (CART_LINE_ID) references CART_LINE(ID);
ALTER TABLE CART_LINE ADD constraint foreign key (PRODUCT_ID) references PRODUCT(ID);
ALTER TABLE CART_LINE ADD constraint foreign key (CART_ID) references CART(ID);
ALTER TABLE CART_LINE ADD constraint foreign key (VARIANT_ID) references VARIANT(ID);
ALTER TABLE PRODUCT ADD constraint foreign key (CATEGORY_ID) references CATEGORY(ID);
ALTER TABLE VARIANT ADD constraint foreign key (PRODUCT_ID) references PRODUCT(ID);
ALTER TABLE ORDERS ADD constraint foreign key (USER_ID) references USER(ID);
ALTER TABLE ORDERS ADD constraint foreign key (ORDER_LINE_ID) references ORDER_LINE(ID);
ALTER TABLE ORDER_LINE ADD constraint foreign key (CART_LINE_ID) references CART_LINE(ID);