CREATE DATABASE STUDENT_MANAGEMENT;
USE STUDENT_MANAGEMENT;
CREATE TABLE STUDENT (
ID INT auto_increment PRIMARY KEY,
NAME varchar(50) NOT NULL,
PHONE VARCHAR(50) NOT NULL UNIQUE,
ADDRESS VARCHAR(250) NOT NULL
);
CREATE TABLE CLASS (
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(10) NOT NULL
);
CREATE TABLE TEACHER (
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
PHONE VARCHAR(10) NOT NULL
);
ALTER TABLE STUDENT ADD column CLASS_ID INT NOT NULL; 
ALTER TABLE STUDENT ADD constraint foreign key (CLASS_ID) references CLASS(ID);
ALTER TABLE TEACHER ADD column CLASS_ID INT NOT NULL;
ALTER TABLE TEACHER ADD constraint foreign key (CLASS_ID) references CLASS(ID);