CREATE DATABASE UNIVERSITY_STUDENT_MANAGEMENT;
USE UNIVERSITY_STUDENT_MANAGEMENT;
CREATE TABLE CLASS (
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(60) NOT NULL,
STARTDATE DATETIME NOT NULL,
STATUS bit
);
CREATE TABLE STUDENT (
ID INT auto_increment primary KEY,
NAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50),
PHONE VARCHAR(20),
STATUS BIT,
CLASS_ID INT NOT NULL
);
CREATE TABLE SUBJECT (
ID INT auto_increment PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
CREDIT TINYINT NOT NULL default 1, CHECK (CREDIT >= 1),
STATUS BIT default 1
);
CREATE TABLE MARK (
ID INT AUTO_INCREMENT PRIMARY KEY,
SUBJECT_ID INT NOT NULL UNIQUE,
STUDENT_ID INT NOT NULL UNIQUE,
MARK float default 0, CHECK (MARK BETWEEN 0 AND 100),
EXAM_TIMES TINYINT DEFAULT 1
);
ALTER TABLE STUDENT ADD CONSTRAINT FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID);
ALTER TABLE MARK ADD CONSTRAINT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(ID);
ALTER TABLE MARK ADD CONSTRAINT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID);